#cloud-config

# Application ID
{% set CLIENT_ID = '3zs4x7w4m7xuk8xkgkycu934y9dvmqu785ca' %}

# Tenant ID
{% set ISSUER_ID = 'f4e2tqd8jg6h92qmxse1nmg535qjm84fbadr' %}

package_update: true
package_upgrade: true

apt:
  sources:
      source1:
          source: 'ppa:ubuntu-enterprise-desktop/authd'

# deb and snap install
packages:
  - authd

snap:
 commands:
   - ['install', 'authd-msentraid']

runcmd:
  - sed -i 's|<CLIENT_ID>|{{ CLIENT_ID }}|g; s|<ISSUER_ID>|{{ ISSUER_ID }}|g' /var/snap/authd-msentraid/current/broker.conf
  - echo 'ssh_allowed_suffixes = @test.onmicrosoft.com' >> /var/snap/authd-msentraid/current/broker.conf
  - sed -i 's/^\(LOGIN_TIMEOUT\t\t\)[0-9]\+/\1360/' /etc/login.defs
  - mkdir -p /etc/authd/brokers.d/
  - cp /snap/authd-msentraid/current/conf/authd/msentraid.conf /etc/authd/brokers.d/
  - snap restart authd-msentraid
  - systemctl restart authd
  - systemctl restart ssh
  - |
    # Create directory for devcontainer.json and write its content
    mkdir -p /home/vscode/.devcontainer
    cat <<'EOF' > /home/vscode/.devcontainer/devcontainer.json
    {
      "image": "ghcr.io/amerintlxperts/devcontainer:latest",
      "initializeCommand": "docker pull ghcr.io/amerintlxperts/devcontainer:latest",
      "runArgs": [
        "--hostname=devcontainer"
      ]
    }
    EOF
  - chown -R vscode:vscode /home/vscode/.devcontainer
  - chmod 0644 /home/vscode/.devcontainer/devcontainer.json
  - curl -fsSL https://get.docker.com | sh && usermod -aG docker vscode
  - useradd -m -d /home/actions-runner -s /bin/bash actions-runner && usermod -G docker actions-runner && cd /home/actions-runner && curl -o actions-runner-linux-x64-2.323.0.tar.gz -L https://github.com/actions/runner/releases/download/v2.323.0/actions-runner-linux-x64-2.323.0.tar.gz && tar xzf ./actions-runner-linux-x64-2.323.0.tar.gz && su - actions-runner -c "./config.sh --url https://github.com/amerintlxperts/devcontainers --token AG2O2OGY3TKAKEEEDC43XXLH7P62G" && ./svc.sh install && ./svc.sh start
  - |
    echo "Checking if reboot is required..."
    if [ -f /var/run/reboot-required ]; then
      echo "Reboot required. Initiating reboot..."
      reboot
    else
      echo "No reboot required."
    fi
